apiVersion: v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: ez-chef-mongo-1
  replicas: 1
  template:
    metadata:
      labels:
        app: ez-chef-mongo-1
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  labels:
    app: ez-chef-mongo-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: ez-chef-mongo-1
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: NodePort
  selector:
    app: ez-chef-mongo-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ez-chef-api-server-1
spec:
  selector:
    matchLabels:
      app: ez-chef-api-server-1
  replicas: 1
  template:
    metadata:
      labels:
        app: ez-chef-api-server-1
    spec:
      containers:
        - name: ez-chef-api-server-1
          image: api-server
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-data