version: "3"

services:
  react-app:
    image: react-app-dev
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - ez-chef
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  api-server:
    image: api-server
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - ez-chef
    volumes:
      - ./backend/:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - ez-chef
    volumes:
      - mongo-data:/data/db

networks:
  ez-chef:
    driver: bridge

volumes:
  mongo-data:
    driver: local
